global:
  name: consul
  image: hashicorppreview/consul:1.16-dev
  imageK8S: hashicorppreview/consul-k8s-control-plane:1.2.0-dev
  imageConsulDataplane: hashicorppreview/consul-dataplane:1.2.0-rc1-dev
  logLevel: trace
  tls:
    enabled: true
server:
  replicas: 1
  extraConfig: '{"log_level": "TRACE"}'
connectInject:
  enabled: true
  default: true
  apiGateway:
    managedGatewayClass:
      serviceType: NodePort
controller:
  enabled: true