---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vaultpkisecret-sample
spec:
  # Use the default Auth Method that we deploy via helm so do not specify a vaultAuthRef
  mount: pki
  role: secret
  destination:
    type: kubernetes.io/tls
    name: pki1
    create: true
  # This is the part we need to figure out cert wise
  commonName: consul.example.com
  format: pem
  clear: true
  expiryOffset: 30s
  ttl: 1h
